sudo: required
services:
- docker
language: python
python:
- '3.6'
before_install:
- docker version
- docker info
install:
- nvm install --lts
- npm install newman
- pip install -r requirements.txt
- pip install -r test-requirements.txt
- pip install nose
- pip install Flask-Testing
before_script:
- node --version
- npm --version
- node_modules/.bin/newman --version
script:
- python -m unittest discover
- docker build -t melvio/devops2021-lab2 .
- docker run --name example_api -d -t -p 127.0.0.1:8080:8080 melvio/devops2021-lab2
- docker ps
- count=0 && until $(curl --output /dev/null --silent --head --fail http://localhost:8080);
  do printf '.' && sleep 3 && count=$((count+1)) && if [ $count -gt 5 ]; then break;
  fi; done
- docker logs example_api
- node_modules/.bin/newman run tests/postman_collection.json -e tests/postman_environment.json
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker tag melvio/devops2021-lab2 melvio/devops2021-lab2
- docker push melvio/devops2021-lab2:latest
env:
  global:
  - secure: mURYBTF67K/W153PUXS4oB6gr07nQkHNCh3C/UuZxI8HJg/JxZF+MWRQ4/3ZGFrtgWO7lSToKOrAQjRNIG8C0QGYxJSRBvp2V2Z0AbGeHCqLIje9YJxD3CuJ9kNro6mqQrCCLcDYHgqbQAhqR/ZcWm8jqRUZ62khu+QU6vSpv5mi91dc10SX+MOk3SfBoaCfn7kY/UM/gWz2tVyrU/Eo68vNLhz9FOLIJPfXAzTVLi42s5BI8Dxa60cHuHI5VewFupIUDZMxyNZ9R9sQ4Z8n0NjD19/h9hgt19tHQ7fvmw2eUb0Ef6/gKIWsrK4lHIO80oIMcBiZ9YVDuOBANRV5KeMjs2Sj/2yP5ZAW1ewGeRfsnDA83nsNGOtfaV3u4hld20SAmog6c0HEY3x3lnkNR0B6PnEAf1PiHqsyGqumnFKjuKB/4EAaw0pY9onADRg6biUtOlFROh6K2G43SoZiygrgWP+YTFmr7+AP359l2tDXrlTgelqW7iAY8g73pwd9hZrYVR1KsJYxd/j7Hi/UCcXcZ4qawKvPMqEHxygyqD/fJiLNpIv9YPfXpvciHGZaxzvlmx98YzH8ilT51H0CmgR/yKg2J/lMZ9LhPmAD5QqWN2175nUgZoLaY7hhbzqtu9uZplNuM/Gxrb6GeZpHNwKF2NkwDzFly5rLJUnNVRM=
  - secure: JEb1tB0zflgMaMbuI9zkhrdVaQs9pA8OyFfvMApdo5w3hUKBkIz6fVxVE5cV88MsoPtE/y+mhekasidLxncEqdZ6ilXvqqf+kYAAV6UOB6HPAe5BQfILfxERnTlbad3WDPvERbG0A/EeHjpXwiqmivDq7LO9PX42hrXrnt/jwaD9MgGdKrmzBz9y3JMajjJCQM/CXIrdM3rRpnUvXi56EWhDCeBFBXGsryRW/idX56fO9scGXf/WBXq2jKDp8P2o5X9CnTQTWf2tdkP3XxSrble8g7m/tfO0BEQnqhpTh0asJsC+trhub4RDwQGhT+//mMs868J0SP5Op/3s2RxrBXhQNkbyr8dfK44w+5/ECznNAfNgM+uTg2TzNSn33KoqzkZNrTcV1yT/4VO4n7z/HhqRKQyTT1J2XGgF8VTrf0H9WHNsqzKIv4klwnUEuUpF4mXhdgQvs1Kgnl/vBZJufpiVIFVYnyreQ5XHsavPEYsXBZMbWz7k3S9cUa7EH4PwOJHbJUurWw6U6kVnHOcEBH8laig6Hs/CwECfVVMtuazF0gV5BwcR/SLhg8YasNKdvx3FeRpikCtG+Zz+vlbmLHfCkfbg+VacMYQjY7JndmGH4cdhIBLQTlNbvKGQSEQTsqOcVrD/wZKEX+eQ2QKOVnPJbYfoRDWQpIPojsnqLi8=
