swagger: "2.0"
info:
  description: "Swagger tutorial"
  version: "1.0.0"
  title: "Swagger tutorial"
basePath: "/service-api"
schemes:
- "http"
paths:
  /student:
    post:
      summary: "Add a new student"
      description: ""
      operationId: "addStudent"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Student object that needs to be added"
        required: true
        schema:
          $ref: "#/definitions/Student"
      responses:
        200:
          description: "successful operation"
          schema: 
            type: "integer"
            format: "int64"
        409:
          description: "already exists"
        405:
          description: "Invalid input"
  /student/{student_id}:
    get:
      summary: "Find student by ID"
      description: "Returns a single student"
      operationId: "getStudentById"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "student_id"
        in: "path"
        description: "ID of student to return"
        required: true
        type: "integer"
        format: "int64"
      - name: "subject"
        in: "query"
        description: "The subject name"
        required: false
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Student"
        400:
          description: "Invalid ID supplied"
        404:
          description: "student not found"
    delete:
      description: ""
      operationId: "deleteStudent"
      produces:
        - "application/xml"
        - "application/json"
      # exercise 2.1b
      parameters:
        - name: "student_id"
          in: "path"
          description: "ID of student to delete"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Student"
        400:
          description: "Invalid ID supplied"
        404:
         description: "student not found"
# documentation:
# * <https://swagger.io/docs/specification/data-models/> (3.0)
# * <https://swagger.io/specification/v2/> (2.0)

# exercise 2.1a
definitions:
  Student:
    type: "object"
    properties:
      student_id:
        type: "integer"
        format: "int64"
      first_name:
        type: "string"
      last_name:
        type: "string"
      # <https://swagger.io/docs/specification/data-models/dictionaries/>
      # <https://www.howtobuildsoftware.com/index.php/how-do/Uad/swagger-swagger-ui-how-to-define-a-map-in-swagger>
      grades:
        type: "object"
        # additionalProperties specifies the type of values in a map
        additionalProperties:
          type: "integer"
          format: "int64"





